from __future__ import annotations

"""Agent conversation loop orchestration.

This module implements :func:`run_loop`, the core async coroutine that drives an
agent through repeated ``chat() → tool_call → tool_result`` cycles until the LLM
produces a final text answer or a hard cap is breached.

Responsibilities of this module
---------------------------------
- Conversation orchestration (messages accumulation, iteration control).
- Cap enforcement: iteration count, total tokens, total cost, wall-clock runtime.
- Tool dispatch with allow-list checking and ``ToolError`` recovery.
- Emitting :class:`LoopEvent` records via a caller-supplied async sink.

Non-responsibilities
---------------------
- Secret redaction — the runner (issue #26) attaches a redacting wrapper around
  the ``event_sink`` before passing it here.  The loop emits raw text.
- Persistence — the runner persists ``AgentStep`` rows via the ``event_sink``.
- Workspace lifecycle — ``WorkspaceInfo`` is created by the runner and passed in.
"""

import asyncio
import time
from collections.abc import Awaitable, Callable
from dataclasses import dataclass
from typing import Any

from backend.agents.tools.base import Tool, ToolError, WorkspaceContext
from backend.agents.workspace import WorkspaceInfo
from backend.llm.base import LLMMessage, LLMProvider, LLMResponse
from backend.models.enums import AgentStepType
from backend.providers.base import PlatformProvider

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class LoopCaps:
    """Hard limits enforced by the agent loop.

    All budget caps are evaluated **after** each LLM call so we always have
    accurate token/cost figures before deciding whether to continue.

    Attributes:
        max_iterations: Maximum number of LLM calls (inclusive). The loop
            returns ``error="iteration_cap"`` when this is exhausted.
        max_tokens_total: Combined input+output token budget. Breaching this
            raises :class:`LoopBudgetExceeded` with ``reason="tokens"``.
        max_cost_usd: Maximum cumulative cost in USD. Breaching this raises
            :class:`LoopBudgetExceeded` with ``reason="cost"``.
        max_runtime_seconds: Wall-clock cap checked at the **top** of each
            iteration (before the LLM call). Breaching this raises
            :class:`LoopBudgetExceeded` with ``reason="runtime"``.
    """

    max_iterations: int = 30
    max_tokens_total: int = 200_000
    max_cost_usd: float = 5.0
    max_runtime_seconds: int = 900


# ---------------------------------------------------------------------------
# Event model
# ---------------------------------------------------------------------------


@dataclass
class LoopEvent:
    """One observable step emitted via ``event_sink`` for the runner to persist.

    Attributes:
        step_index: Monotonically increasing counter across the entire run.
            No gaps; no duplicates.
        step_type: Semantic category of the step (see :class:`AgentStepType`).
        prompt_hash: Stable hash of the initial system+user prompt pair.
            Only set on the first ``llm_call`` event; ``None`` on all others.
        tool_name: Populated for ``tool_call`` and ``tool_result`` events.
        tool_args: Raw arguments dict supplied to the tool.
        tool_result: Stringified output (or error message) from the tool.
        input_tokens: Prompt tokens consumed by this LLM call.
        output_tokens: Completion tokens generated by this LLM call.
        latency_ms: Wall-clock duration of the LLM or tool call in ms.
        status: ``"ok"`` | ``"error"`` | ``"budget"`` | ``"cancelled"``.
    """

    step_index: int
    step_type: AgentStepType
    prompt_hash: str | None = None
    tool_name: str | None = None
    tool_args: dict[str, Any] | None = None
    tool_result: str | None = None
    input_tokens: int = 0
    output_tokens: int = 0
    latency_ms: int = 0
    status: str = "ok"


# ---------------------------------------------------------------------------
# Result model
# ---------------------------------------------------------------------------


@dataclass
class LoopResult:
    """Terminal outcome of a :func:`run_loop` call.

    Attributes:
        success: ``True`` when the LLM produced a non-empty final answer.
        final_message: The LLM's final text response. Empty string on failure.
        total_input_tokens: Sum of all input tokens across every LLM call.
        total_output_tokens: Sum of all output tokens across every LLM call.
        total_cost_usd: Sum of all per-call cost estimates.
        iterations: Number of LLM calls that were made.
        error: Machine-readable failure reason when ``success=False``.
            One of ``"iteration_cap"`` | ``"empty_response"`` | ``None``.
    """

    success: bool
    final_message: str
    total_input_tokens: int
    total_output_tokens: int
    total_cost_usd: float
    iterations: int
    error: str | None = None


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------


class LoopCancelled(Exception):
    """Raised when ``cancel_event`` is set during the loop.

    The terminal :class:`LoopEvent` with ``status="cancelled"`` is emitted
    **before** this exception propagates to the caller.
    """


class LoopBudgetExceeded(Exception):
    """Raised when any hard cap is breached after an LLM call.

    The terminal :class:`LoopEvent` with ``status="budget"`` is emitted
    **before** this exception propagates to the caller.

    Attributes:
        reason: Human-readable cap label.
            One of ``"runtime"`` | ``"tokens"`` | ``"cost"``.
    """

    def __init__(self, reason: str) -> None:
        """Initialise with the cap label that was breached.

        Args:
            reason: ``"runtime"`` | ``"tokens"`` | ``"cost"``.
        """
        super().__init__(reason)
        self.reason = reason


# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------


async def run_loop(
    *,
    llm: LLMProvider,
    workspace: WorkspaceInfo,
    provider: PlatformProvider,
    system_prompt: str,
    user_prompt: str,
    tools: dict[str, Tool],
    caps: LoopCaps,
    event_sink: Callable[[LoopEvent], Awaitable[None]],
    cancel_event: asyncio.Event,
    prompt_hash: str | None = None,
) -> LoopResult:
    """Drive the agent through plan -> tool -> observe cycles until done or capped.

    The loop maintains a growing ``messages`` list (system, user, assistant,
    tool, …) and calls the LLM repeatedly until one of the following terminal
    conditions is met:

    - The LLM returns non-empty text with no tool_calls (success).
    - The LLM returns empty text with no tool_calls (``error="empty_response"``).
    - ``caps.max_iterations`` LLM calls have been made (``error="iteration_cap"``).
    - A budget cap fires (raises :class:`LoopBudgetExceeded`).
    - ``cancel_event`` is set (raises :class:`LoopCancelled`).

    :class:`LoopEvent` records are emitted to *event_sink* for every ``llm_call``,
    ``tool_call``, ``tool_result``, and the terminal ``final`` step.  The runner is
    responsible for redacting secrets inside the sink before persisting.

    Tool errors (``ToolError``) are **not** fatal.  They are reported as
    ``tool_result`` events with ``status="error"`` and fed back to the LLM so it
    can recover.  Same for tools not present in the *tools* allow-list.

    Args:
        llm: LLM provider implementing :class:`~backend.llm.base.LLMProvider`.
        workspace: Checked-out repository workspace.  Used to build the
            :class:`~backend.agents.tools.base.WorkspaceContext` passed to tools.
        provider: Platform provider (GitHub / GitLab / Azure DevOps) forwarded
            as-is to tools that need API access.
        system_prompt: System instruction for the conversation.
        user_prompt: Initial user turn (the task description).
        tools: Allow-listed tools keyed by name.  The loop will NOT dispatch
            tools whose names are absent from this mapping.
        caps: Hard limits on iterations, tokens, cost, and runtime.
        event_sink: Async callable that receives every :class:`LoopEvent`.
            Called with ``await``; must be fast (do not block the loop).
        cancel_event: When set, the loop exits cleanly at the next iteration
            boundary and raises :class:`LoopCancelled`.
        prompt_hash: Optional stable hash of the initial prompts; attached to
            the first ``llm_call`` event only.

    Returns:
        :class:`LoopResult` describing the terminal state.

    Raises:
        LoopCancelled: If ``cancel_event`` fires during the loop.
        LoopBudgetExceeded: If any hard cap is breached (token, cost, runtime).
    """
    start = time.monotonic()
    step_index = 0

    messages: list[LLMMessage] = [
        LLMMessage(role="system", content=system_prompt),
        LLMMessage(role="user", content=user_prompt),
    ]

    total_input = 0
    total_output = 0
    total_cost = 0.0

    ws_ctx = WorkspaceContext(path=workspace.path, head_sha=workspace.head_sha)

    for iteration in range(caps.max_iterations):
        # ------------------------------------------------------------------
        # 1. Cancellation check — evaluated at the top of every iteration.
        # ------------------------------------------------------------------
        if cancel_event.is_set():
            await event_sink(
                LoopEvent(
                    step_index=step_index,
                    step_type=AgentStepType.final,
                    status="cancelled",
                )
            )
            raise LoopCancelled

        # ------------------------------------------------------------------
        # 2. Wall-clock runtime check — also before the LLM call.
        # ------------------------------------------------------------------
        elapsed = time.monotonic() - start
        if elapsed > caps.max_runtime_seconds:
            await event_sink(
                LoopEvent(
                    step_index=step_index,
                    step_type=AgentStepType.final,
                    status="budget",
                )
            )
            raise LoopBudgetExceeded("runtime")

        # ------------------------------------------------------------------
        # 3. LLM call.
        # ------------------------------------------------------------------
        llm_start = time.monotonic()
        response: LLMResponse = await llm.chat(
            messages=messages,
            tools=_tool_schemas(tools),
            max_tokens=4096,
        )
        llm_latency = int((time.monotonic() - llm_start) * 1000)

        total_input += response.input_tokens
        total_output += response.output_tokens
        total_cost += response.cost_usd

        await event_sink(
            LoopEvent(
                step_index=step_index,
                step_type=AgentStepType.llm_call,
                # Only attach the prompt hash on the very first LLM call.
                prompt_hash=prompt_hash if step_index == 0 else None,
                input_tokens=response.input_tokens,
                output_tokens=response.output_tokens,
                latency_ms=llm_latency,
            )
        )
        step_index += 1

        # ------------------------------------------------------------------
        # 4. Budget checks — evaluated AFTER the offending call.
        # ------------------------------------------------------------------
        if total_input + total_output > caps.max_tokens_total:
            await event_sink(
                LoopEvent(
                    step_index=step_index,
                    step_type=AgentStepType.final,
                    status="budget",
                )
            )
            raise LoopBudgetExceeded("tokens")

        if total_cost > caps.max_cost_usd:
            await event_sink(
                LoopEvent(
                    step_index=step_index,
                    step_type=AgentStepType.final,
                    status="budget",
                )
            )
            raise LoopBudgetExceeded("cost")

        # ------------------------------------------------------------------
        # 5. Tool dispatch (when the LLM requests tool calls).
        # ------------------------------------------------------------------
        if response.tool_calls:
            # Append the assistant turn (may carry partial text + the tool
            # call declarations) so future LLM calls have full context.
            messages.append(
                LLMMessage(
                    role="assistant",
                    content=response.text or "",
                )
            )

            for tc in response.tool_calls:
                await event_sink(
                    LoopEvent(
                        step_index=step_index,
                        step_type=AgentStepType.tool_call,
                        tool_name=tc.name,
                        tool_args=tc.arguments,
                    )
                )
                step_index += 1

                # Allow-list guard — do NOT raise; let the LLM recover.
                if tc.name not in tools:
                    err_msg = f"Tool '{tc.name}' is not in the allow-list"
                    await event_sink(
                        LoopEvent(
                            step_index=step_index,
                            step_type=AgentStepType.tool_result,
                            tool_name=tc.name,
                            tool_result=err_msg,
                            status="error",
                        )
                    )
                    step_index += 1
                    messages.append(LLMMessage(role="tool", content=err_msg))
                    continue

                # Dispatch the tool call.
                tool = tools[tc.name]
                tool_start = time.monotonic()
                try:
                    result = await tool(tc.arguments, workspace=ws_ctx, provider=provider)
                    tool_latency = int((time.monotonic() - tool_start) * 1000)
                    await event_sink(
                        LoopEvent(
                            step_index=step_index,
                            step_type=AgentStepType.tool_result,
                            tool_name=tc.name,
                            tool_result=result.output,
                            latency_ms=tool_latency,
                            status="ok" if result.ok else "error",
                        )
                    )
                    step_index += 1
                    messages.append(LLMMessage(role="tool", content=result.output))
                except ToolError as exc:
                    tool_latency = int((time.monotonic() - tool_start) * 1000)
                    err_msg = f"ToolError: {exc}"
                    await event_sink(
                        LoopEvent(
                            step_index=step_index,
                            step_type=AgentStepType.tool_result,
                            tool_name=tc.name,
                            tool_result=err_msg,
                            latency_ms=tool_latency,
                            status="error",
                        )
                    )
                    step_index += 1
                    messages.append(LLMMessage(role="tool", content=err_msg))
                # ToolError is intentionally NOT re-raised.  Tool failures are
                # observable (status="error" event + role=tool message) but do
                # not terminate the loop — the LLM gets to react and retry.

            # Continue to the next iteration so the LLM can react to results.
            continue

        # ------------------------------------------------------------------
        # 6. No tool calls — treat response.text as the final answer.
        # ------------------------------------------------------------------
        if response.text and response.text.strip():
            await event_sink(
                LoopEvent(
                    step_index=step_index,
                    step_type=AgentStepType.final,
                )
            )
            return LoopResult(
                success=True,
                final_message=response.text,
                total_input_tokens=total_input,
                total_output_tokens=total_output,
                total_cost_usd=total_cost,
                iterations=iteration + 1,
            )

        # Empty text + no tool calls — unrecoverable, report and exit.
        await event_sink(
            LoopEvent(
                step_index=step_index,
                step_type=AgentStepType.final,
                status="error",
            )
        )
        return LoopResult(
            success=False,
            final_message="",
            total_input_tokens=total_input,
            total_output_tokens=total_output,
            total_cost_usd=total_cost,
            iterations=iteration + 1,
            error="empty_response",
        )

    # The ``for`` loop exhausted ``range(caps.max_iterations)`` without a
    # terminal answer — the LLM kept requesting tool calls every iteration.
    await event_sink(
        LoopEvent(
            step_index=step_index,
            step_type=AgentStepType.final,
            status="error",
        )
    )
    return LoopResult(
        success=False,
        final_message="",
        total_input_tokens=total_input,
        total_output_tokens=total_output,
        total_cost_usd=total_cost,
        iterations=caps.max_iterations,
        error="iteration_cap",
    )


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------


def _tool_schemas(tools: dict[str, Tool]) -> list[dict[str, Any]]:
    """Build an LLM-facing tool schema list from the given allow-list.

    Args:
        tools: Mapping of tool name to :class:`~backend.agents.tools.base.Tool`
            instances (the loop's allow-list).

    Returns:
        A list of ``{"name": ..., "description": ..., "parameters": ...}``
        dicts suitable for passing to :meth:`~backend.llm.base.LLMProvider.chat`.
    """
    return [
        {
            "name": t.name,
            "description": t.description,
            "parameters": t.arguments_schema,
        }
        for t in tools.values()
    ]
